title: hermanl0â€™s Personal Site
description: A simple portfolio and blog powered by Jekyll and GitHub Pages.
url: "https://hermanl0.github.io"
author: hermanl0

remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown
